//! cfdb-recall — measure cfdb-extractor recall against `cargo public-api`
//! ground truth, per RFC-029 §13 acceptance gate Item 2.
//!
//! **Why this crate exists.** The original RFC sketched the recall gate as
//! `rg -c '^pub (struct|enum|trait|fn|type|const)' crates/$c/src/` against a
//! query count from the store. That is broken in three ways: (1) the ratio
//! is count-based, so two items with the same local name collapse into one
//! denominator slot; (2) `rg` cannot see items produced by macro expansion
//! (`define_id!`, `#[derive(...)]`, `paste!`, etc.); (3) a `pub` keyword
//! inside a `pub mod { ... }` block that is already public produces nested
//! matches `rg` cannot disambiguate. QA-2 during RFC council rejected the
//! original formulation and mandated `cargo public-api` (or `rustdoc
//! --output-format json`) as the canonical source of truth. This crate is
//! the replacement.
//!
//! **Dependency rule.** The pure logic in this module (sets, ratios, audit
//! carve-out) has zero I/O and zero dependencies on `rustdoc-json` or
//! `public-api`. Those crates live in the adapter modules and the binary
//! entry point. Tests for the logic run against synthetic inputs so they do
//! not require a nightly toolchain or a network connection.
//!
//! **Naming convention.** `PublicItem::qname` is the fully-qualified path
//! from the crate root: `crate_name::module::path::item`. The crate name is
//! the Cargo package name with hyphens converted to underscores — the same
//! convention `cfdb-extractor` applies at `lib.rs:145` and that `rustdoc`
//! produces by default. Items at the crate root appear as
//! `crate_name::item`; items inside impls appear as
//! `crate_name::module::Type::method` — this matches the extractor's
//! `visit_impl_item_fn` at `lib.rs:529`.

use std::collections::BTreeSet;

pub mod adapters;

/// A normalized, comparable reference to a public item.
///
/// The qname is the ONLY field: two public items are equal iff their qnames
/// are equal. We intentionally drop item kind (`fn` vs `struct` vs …) from
/// the equality check because the extractor's qname is unique across kinds
/// within a crate (Rust's namespace rules forbid a struct and a function
/// with the same qname at the same path). Including kind would create
/// spurious mismatches when a normalization step on one side of the compare
/// renders a trait method as `fn` and the other renders it as `method`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct PublicItem {
    pub qname: String,
}

impl PublicItem {
    pub fn new(qname: impl Into<String>) -> Self {
        Self {
            qname: qname.into(),
        }
    }
}

/// A set of items the recall gate should ignore when computing the
/// denominator — typically items generated by macros the extractor cannot
/// see (`define_id!`, `#[derive]` expansions).
///
/// The audit list is LOAD-BEARING for the recall formula: items in the list
/// are subtracted from BOTH the numerator and the denominator, which is
/// equivalent to treating them as "not part of the surface we are measuring
/// recall against". An audit entry is a statement "this item is known to be
/// macro-generated and therefore not visible to syn — please do not hold
/// the extractor responsible for it".
#[derive(Debug, Clone, Default)]
pub struct AuditList {
    items: BTreeSet<PublicItem>,
}

impl AuditList {
    pub fn new() -> Self {
        Self::default()
    }

    /// Build an `AuditList` from a collection of items.
    ///
    /// Named `from_items` rather than `from_iter` to avoid shadowing the
    /// standard `FromIterator::from_iter` trait method, which clippy
    /// (`should_implement_trait`) flags as confusing. We deliberately do
    /// not implement `FromIterator` because the item set is conceptually
    /// a configuration input, not a freely-constructed collection.
    pub fn from_items<I: IntoIterator<Item = PublicItem>>(iter: I) -> Self {
        Self {
            items: iter.into_iter().collect(),
        }
    }

    pub fn contains(&self, item: &PublicItem) -> bool {
        self.items.contains(item)
    }

    pub fn len(&self) -> usize {
        self.items.len()
    }

    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    pub fn items(&self) -> &BTreeSet<PublicItem> {
        &self.items
    }
}

/// The minimum per-crate recall the v0.1 acceptance gate requires.
///
/// Defined in RFC-029 §13 Item 2 (revised). The value is a `const` in
/// source deliberately, per CLAUDE.md §6 rule 8: every metric threshold in
/// the qbot ecosystem is a `const`, never a baseline file. Raising this
/// threshold requires a reviewed PR against this constant.
pub const DEFAULT_THRESHOLD: f64 = 0.95;

/// Result of a single-crate recall computation.
#[derive(Debug, Clone, PartialEq)]
pub struct RecallReport {
    /// Cargo package name with hyphens — the identifier a human recognizes.
    pub crate_name: String,
    /// Threshold the gate required (e.g. 0.95).
    pub threshold: f64,
    /// Every public item the ground truth reported, before audit carve-out.
    pub total_public: usize,
    /// Public items after subtracting the audit list — the denominator of
    /// the recall ratio.
    pub adjusted_denominator: usize,
    /// Public items the extractor DID emit (numerator).
    pub matched: usize,
    /// Items the ground truth reported, the extractor missed, and the audit
    /// list did NOT carve out. These are the REAL gaps that fail the gate.
    pub missing: Vec<PublicItem>,
    /// Items the ground truth reported and the audit list carved out. Kept
    /// for reporting so `KNOWN_GAPS.md` can show them.
    pub audited: Vec<PublicItem>,
}

impl RecallReport {
    /// `|extracted ∩ (public − audit)| / |public − audit|`. Returns `None`
    /// for the empty-denominator edge case — a crate with zero public items
    /// has no meaningful recall and callers must handle this explicitly
    /// (the binary treats it as "vacuously passing with a warning"; the
    /// gate does not fail on an empty denominator).
    pub fn recall(&self) -> Option<f64> {
        if self.adjusted_denominator == 0 {
            None
        } else {
            Some(self.matched as f64 / self.adjusted_denominator as f64)
        }
    }

    /// True iff recall is ≥ threshold. An empty denominator passes
    /// vacuously — see [`Self::recall`] for the rationale.
    pub fn passes(&self) -> bool {
        match self.recall() {
            None => true,
            Some(r) => r >= self.threshold,
        }
    }
}

/// Pure recall computation. Takes the three sets as input and produces a
/// report. Zero I/O, zero subprocess invocation — this is the business rule
/// the TDD tests exercise in isolation.
///
/// The formula intentionally subtracts the audit list from BOTH numerator
/// and denominator. An audited item that the extractor DID emit should not
/// count toward recall either — if the audit list says "this item is
/// carved out", we treat it as outside the measurement surface entirely.
pub fn compute_recall(
    crate_name: impl Into<String>,
    public: &BTreeSet<PublicItem>,
    extracted: &BTreeSet<PublicItem>,
    audit: &AuditList,
    threshold: f64,
) -> RecallReport {
    let crate_name = crate_name.into();

    // Apply audit carve-out: remove audited items from the surface.
    let adjusted: BTreeSet<&PublicItem> = public.iter().filter(|it| !audit.contains(it)).collect();
    let adjusted_denominator = adjusted.len();

    // Numerator: items in adjusted set that the extractor also emitted.
    let matched = adjusted
        .iter()
        .filter(|it| extracted.contains(**it))
        .count();

    // Missing: adjusted items the extractor did NOT emit. Sorted by qname
    // for deterministic reporting (critical for the `KNOWN_GAPS.md` diff
    // stability — any reorder would produce spurious commit churn).
    let mut missing: Vec<PublicItem> = adjusted
        .iter()
        .filter(|it| !extracted.contains(**it))
        .map(|it| (*it).clone())
        .collect();
    missing.sort();

    // Audited: items in both `public` and the audit list. Sorted for the
    // same reason.
    let mut audited: Vec<PublicItem> = public
        .iter()
        .filter(|it| audit.contains(it))
        .cloned()
        .collect();
    audited.sort();

    RecallReport {
        crate_name,
        threshold,
        total_public: public.len(),
        adjusted_denominator,
        matched,
        missing,
        audited,
    }
}

// ── Unit tests (TDD — business rules in isolation) ──────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn item(qname: &str) -> PublicItem {
        PublicItem::new(qname)
    }

    fn set<I: IntoIterator<Item = PublicItem>>(items: I) -> BTreeSet<PublicItem> {
        items.into_iter().collect()
    }

    // ── Recall formula (numerator / denominator) ──────────────

    #[test]
    fn recall_is_perfect_when_extracted_matches_public() {
        let public = set([item("c::foo"), item("c::bar")]);
        let extracted = public.clone();
        let audit = AuditList::new();
        let report = compute_recall("c", &public, &extracted, &audit, 0.95);
        assert_eq!(report.matched, 2);
        assert_eq!(report.adjusted_denominator, 2);
        assert_eq!(report.recall(), Some(1.0));
        assert!(report.passes());
        assert!(report.missing.is_empty());
    }

    #[test]
    fn recall_is_zero_when_extracted_is_disjoint() {
        let public = set([item("c::foo"), item("c::bar")]);
        let extracted = set([item("c::baz")]);
        let audit = AuditList::new();
        let report = compute_recall("c", &public, &extracted, &audit, 0.95);
        assert_eq!(report.matched, 0);
        assert_eq!(report.adjusted_denominator, 2);
        assert_eq!(report.recall(), Some(0.0));
        assert!(!report.passes());
    }

    #[test]
    fn recall_is_set_based_not_count_based() {
        // Regression guard for the broken `rg -c` approach. Two items with
        // the same *local* name at different qnames must contribute 2 to
        // the denominator, not 1.
        let public = set([item("c::a::foo"), item("c::b::foo")]);
        let extracted = set([item("c::a::foo")]);
        let audit = AuditList::new();
        let report = compute_recall("c", &public, &extracted, &audit, 0.95);
        assert_eq!(report.adjusted_denominator, 2);
        assert_eq!(report.matched, 1);
        assert_eq!(report.recall(), Some(0.5));
    }

    // ── Threshold ─────────────────────────────────────────────

    #[test]
    fn passes_at_exactly_95_percent() {
        // 19/20 = 95% exactly. Must pass (≥, not >).
        let public: BTreeSet<PublicItem> = (0..20).map(|i| item(&format!("c::f{i}"))).collect();
        let extracted: BTreeSet<PublicItem> = (0..19).map(|i| item(&format!("c::f{i}"))).collect();
        let report = compute_recall("c", &public, &extracted, &AuditList::new(), 0.95);
        assert_eq!(report.recall(), Some(0.95));
        assert!(report.passes());
    }

    #[test]
    fn fails_just_below_95_percent() {
        // 18/20 = 90% — below threshold, must fail.
        let public: BTreeSet<PublicItem> = (0..20).map(|i| item(&format!("c::f{i}"))).collect();
        let extracted: BTreeSet<PublicItem> = (0..18).map(|i| item(&format!("c::f{i}"))).collect();
        let report = compute_recall("c", &public, &extracted, &AuditList::new(), 0.95);
        assert_eq!(report.recall(), Some(0.90));
        assert!(!report.passes());
        assert_eq!(report.missing.len(), 2);
    }

    // ── Audit carve-out ───────────────────────────────────────

    #[test]
    fn audit_list_removes_items_from_denominator() {
        // 2 public items, 1 in audit list, 1 extracted. Without audit,
        // recall would be 50% (1/2, fails). With audit removing the
        // uncovered item, recall is 100% (1/1, passes).
        let public = set([item("c::define_id_generated"), item("c::real_fn")]);
        let extracted = set([item("c::real_fn")]);
        let audit = AuditList::from_items([item("c::define_id_generated")]);
        let report = compute_recall("c", &public, &extracted, &audit, 0.95);
        assert_eq!(report.total_public, 2);
        assert_eq!(report.adjusted_denominator, 1);
        assert_eq!(report.matched, 1);
        assert_eq!(report.recall(), Some(1.0));
        assert!(report.passes());
        assert_eq!(report.audited.len(), 1);
    }

    #[test]
    fn audit_list_also_removes_items_from_numerator() {
        // Invariant: an audited item the extractor ALSO emitted must not
        // count toward the numerator — the audit list removes items from
        // the measurement surface entirely, not from the denominator only.
        // This matters because it ensures recall is stable under the
        // symmetric difference test: if audit drops item X from both sides,
        // recall is unchanged by X's extraction status.
        let public = set([item("c::audited"), item("c::real")]);
        let extracted = set([item("c::audited"), item("c::real")]);
        let audit = AuditList::from_items([item("c::audited")]);
        let report = compute_recall("c", &public, &extracted, &audit, 0.95);
        assert_eq!(report.adjusted_denominator, 1);
        assert_eq!(report.matched, 1);
        assert_eq!(report.recall(), Some(1.0));
    }

    #[test]
    fn audit_list_never_references_an_item_not_in_public_set() {
        // An audit entry that does not match any public item is a no-op —
        // it does not affect denominator, numerator, or pass/fail. This is
        // the documented behavior: audit lists are allowed to over-specify
        // so downstream callers can carry forward entries across refactors.
        let public = set([item("c::foo")]);
        let extracted = set([item("c::foo")]);
        let audit = AuditList::from_items([item("c::stale_entry")]);
        let report = compute_recall("c", &public, &extracted, &audit, 0.95);
        assert_eq!(report.adjusted_denominator, 1);
        assert_eq!(report.matched, 1);
        assert_eq!(report.recall(), Some(1.0));
        // No audited item was drawn from the public set.
        assert!(report.audited.is_empty());
    }

    // ── Edge cases ────────────────────────────────────────────

    #[test]
    fn empty_public_set_passes_vacuously() {
        // A crate with zero public items (e.g. a private-only helper crate)
        // has no measurement surface. The gate passes but recall() returns
        // None so callers can report "vacuous" rather than 100%.
        let public = BTreeSet::new();
        let extracted = set([item("c::internal")]);
        let report = compute_recall("c", &public, &extracted, &AuditList::new(), 0.95);
        assert_eq!(report.adjusted_denominator, 0);
        assert_eq!(report.recall(), None);
        assert!(report.passes());
    }

    #[test]
    fn empty_denominator_after_audit_passes_vacuously() {
        // If every public item is audited away, the denominator is zero.
        // Same vacuous-pass semantics as the empty-public case.
        let public = set([item("c::generated1"), item("c::generated2")]);
        let extracted = BTreeSet::new();
        let audit = AuditList::from_items([item("c::generated1"), item("c::generated2")]);
        let report = compute_recall("c", &public, &extracted, &audit, 0.95);
        assert_eq!(report.total_public, 2);
        assert_eq!(report.adjusted_denominator, 0);
        assert_eq!(report.recall(), None);
        assert!(report.passes());
    }

    #[test]
    fn missing_items_are_sorted_for_stable_reporting() {
        // KNOWN_GAPS.md must not churn across runs if the underlying sets
        // are unchanged. Sorting missing + audited is the stability
        // invariant — any reorder would create spurious diffs.
        let public = set([item("c::z_last"), item("c::a_first"), item("c::m_middle")]);
        let extracted = BTreeSet::new();
        let report = compute_recall("c", &public, &extracted, &AuditList::new(), 0.95);
        assert_eq!(
            report
                .missing
                .iter()
                .map(|it| it.qname.as_str())
                .collect::<Vec<_>>(),
            vec!["c::a_first", "c::m_middle", "c::z_last"]
        );
    }

    // ── Extractor-side items that exceed the public surface ──

    #[test]
    fn extractor_superset_does_not_affect_recall() {
        // The extractor emits public AND private items (no vis filter).
        // The recall formula measures intersection with the public set, so
        // extra private items on the extracted side must not affect the
        // ratio. This is the dependency rule in action — the public set is
        // authoritative for what we measure.
        let public = set([item("c::pub_fn")]);
        let extracted = set([
            item("c::pub_fn"),
            item("c::private_helper_1"),
            item("c::private_helper_2"),
        ]);
        let report = compute_recall("c", &public, &extracted, &AuditList::new(), 0.95);
        assert_eq!(report.adjusted_denominator, 1);
        assert_eq!(report.matched, 1);
        assert_eq!(report.recall(), Some(1.0));
    }
}
